export const CREATE_USER_START = 'CREATE_USER_START'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const GET_ACCOUNT_START = 'GET_DATA_START'
export const GET_ACCOUNT_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_ACCOUNT_FAILED = 'GET_DATA_FAILED'

export const ADD_PLANT_START = 'ADD_PLANT_START'
export const ADD_PLANT_SUCCESS = 'ADD_PLANT_SUCCESS'
export const ADD_PLANT_FAILED = 'ADD_PLANT_FAILED'

export const GET_PLANT_START = 'GET_PLANT_START'
export const GET_PLANT_SUCCESS = 'GET_PLANT_SUCCESS'
export const GET_PLANT_FAILED = 'GET_PLANT_FAILED'

export const UPDATE_PLANT_START = 'UPDATE_PLANT_START'
export const UPDATE_PLANT_SUCCESS = 'UPDATE_PLANT_SUCCESS'
export const UPDATE_PLANT_FAILED = 'UPDATE_PLANT_FAILED'

export const DELETE_PLANT_START = 'DELETE_PLANT_START'
export const DELETE_PLANT_SUCCESS = 'DELETE_PLANT_SUCCESS'
export const DELETE_PLANT_FAILED = 'DELETE_PLANT_FAILED'

export const PLANT_ID ='PLANT_ID'